apiVersion: v1
kind: Secret
metadata:
  name: repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Rohith8370/Rails-application.git
  username: Rohith8370
  password: ${{ secrets.TOKEN }}
  type: Opaque
